# Uncomment the next line to define a global platform for your project
 platform :ios, '12.3'

target 'WebScrapping' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebScrapping
  pod 'Alamofire'
  pod 'Kanna'#, :git => :branch => 'feature/v5.2.2'

end
